#
# @lc app=leetcode id=389 lang=python3
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (53.12%)
# Likes:    515
# Dislikes: 231
# Total Accepted:    148K
# Total Submissions: 278.1K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
from collections import Counter
from functools import reduce

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        # O(N)

        # x = Counter(t) - Counter(s)
        # return list(x.keys())[0]


        # return chr(sum(map(ord, t)) - sum(map(ord, s)))
        

        # return chr(reduce(int.__xor__, map(ord, s + t)))

        ch = 0
        for char_ in s:
            ch ^= ord(char_)

        for char_ in t:
            ch ^= ord(char_)

        return chr(ch)

